### ISSUE TITLE
Cannot route on empty project id

### ISSUE THREAD

**Issue by jblythe** [googleapis/python-bigquery-data-exchange#47]
Im not sure how exactly to set the project id for the update call. Create, Get, and Delete all work as expected. Please find details below

#### Environment details

  - OS type and version: macOS Monterey 12.3.1
  - Python version: Python 3.8.9
  - pip version: pip 21.3.1
  - `google-cloud-bigquery-data-exchange` version: 0.3.0

#### Steps to reproduce

  1. Create a Data Exchange
  2. Update a property in the return exchange Object
  3. Create an UpdateDataExchangeRequest with updated exchange Object
  4. Submit request through `update_data_exchange` 

#### Code example

```python
request = bigquery_data_exchange.GetDataExchangeRequest(name="projects/[PROJECT_ID]/locations/US/dataExchanges/[EXCHANGE_ID]")
exchange = client.get_data_exchange(request=request)

exchange.display_name = "SOME NEW DISPLAY NAME"

request = bigquery_data_exchange.UpdateDataExchangeRequest(data_exchange=data_exchange)
response = client.update_data_exchange(request=request)
```

#### Stack trace
```
Traceback (most recent call last):
  File "/opt/66degrees/analyticsHub/venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/66degrees/analyticsHub/venv/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/66degrees/analyticsHub/venv/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Cannot route on empty project id ''"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.190.106:443 {grpc_message:"Cannot route on empty project id \'\'", grpc_status:3, created_time:"2022-10-18T11:12:29.917735-04:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/66degrees/analyticsHub/data_exchange_update.py", line 5, in <module>
    ex = exchange.update()
  File "/opt/66degrees/analyticsHub/google/analytics_hub.py", line 65, in update
    response = client.update_data_exchange(request=request)
  File "/opt/66degrees/analyticsHub/venv/lib/python3.8/site-packages/google/cloud/bigquery_data_exchange_v1beta1/services/analytics_hub_service/client.py", line 1022, in update_data_exchange
    response = rpc(
  File "/opt/66degrees/analyticsHub/venv/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/66degrees/analyticsHub/venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Cannot route on empty project id ''
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by shollyman** [comment]
Investigating this in the backend as issue 255995969

**Comment by shollyman** [comment]
Current status: issue identified, work in progress to resolve this in backend.  ETA unclear at this time for when the fix will reach all regions.

**Comment by shollyman** [comment]
Per backend team, related fix should be fully deployed.  Testing locally I can no longer reproduce the issue.

Closing out this issue, thanks for the report!
